- altered xotcl.m4 to nsf.m4 in    .,    library/xotcl/library/store/XOTclGdbm/,    library/xotcl/library/store/XOTclSdbm/,    library/xotcl/library/xml/TclExpat-1.1/ - removed traces of xotcl.m4 - removed build flags with-nxsh, with-xowish   (since these are scripted now) - removed flag --with-tk (not needed anymore)

diff --git a/library/xotcl/library/store/XOTclSdbm/configure b/library/xotcl/library/store/XOTclSdbm/configure
--- a/library/xotcl/library/store/XOTclSdbm/configure
+++ b/library/xotcl/library/store/XOTclSdbm/configure
@@ -1308,9 +1308,9 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-xotcl=DIR_CONTAINING_XOTCLCONFIG_SH
-            absolute path to xotclConfig.sh,
-           --without-xotcl disables, but this is pointless
+  --with-nsf=DIR_CONTAINING_NSFCONFIG_SH
+            absolute path to nsfConfig.sh,
+           --without-nsf disables, but this is pointless
   --with-tcl              directory containing tcl configuration
                           (tclConfig.sh)
   --with-tclinclude       directory containing the public Tcl header files
@@ -1910,12 +1910,12 @@ ac_configure="$SHELL $ac_aux_dir/configure"  # Please don't use this var.
 #--------------------------------------------------------------------
 
 
-# Check whether --with-xotcl was given.
-if test "${with_xotcl+set}" = set; then
-  withval=$with_xotcl; with_xotcl=$withval
+# Check whether --with-nsf was given.
+if test "${with_nsf+set}" = set; then
+  withval=$with_nsf; with_nsf=$withval
 else
-  { { echo "$as_me:$LINENO: error: --with-xotcl is required" >&5
-echo "$as_me: error: --with-xotcl is required" >&2;}
+  { { echo "$as_me:$LINENO: error: --with-nsf is required" >&5
+echo "$as_me: error: --with-nsf is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -6617,12 +6617,12 @@ done
 
 
 #--------------------------------------------------------------------
-# Load the xotclConfig.sh file
+# Load the nsfConfig.sh file
 #--------------------------------------------------------------------
 
-{ echo "$as_me:$LINENO: Reading file ${with_xotcl}/xotclConfig.sh" >&5
-echo "$as_me: Reading file ${with_xotcl}/xotclConfig.sh" >&6;}
-source ${with_xotcl}/xotclConfig.sh
+{ echo "$as_me:$LINENO: Reading file ${with_nsf}/nsfConfig.sh" >&5
+echo "$as_me: Reading file ${with_nsf}/nsfConfig.sh" >&6;}
+source ${with_nsf}/nsfConfig.sh
 
 #-----------------------------------------------------------------------
 # __CHANGE__
@@ -6685,14 +6685,14 @@ echo "$as_me: error: could not find header file '${srcdir}/$i'" >&2;}
 
 
 
-    vars="-I${with_xotcl}/generic ${XOTCL_BUILD_INCLUDE_SPEC}"
+    vars="-I${with_nsf}/generic ${NSF_BUILD_INCLUDE_SPEC}"
     for i in $vars; do
 	PKG_INCLUDES="$PKG_INCLUDES $i"
     done
 
 
 
-    vars="$XOTCL_BUILD_STUB_LIB_SPEC $XOTCL_BUILD_LIB_SPEC"
+    vars="$NSF_BUILD_STUB_LIB_SPEC $NSF_BUILD_LIB_SPEC"
     for i in $vars; do
 	if test "${TEA_PLATFORM}" = "windows" -a "$GCC" = "yes" ; then
 	    # Convert foo.lib to -lfoo for GCC.  No-op if not *.lib
